name: Build and Push Docker Image

# Chạy workflow này khi có push lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Thiết lập JDK 17 (hoặc phiên bản phù hợp với Spring Boot của bạn)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build ứng dụng Spring Boot và đóng gói thành file JAR
      - name: Build Spring Boot app
        run: ./mvnw clean package

      # Đăng nhập vào Docker Hub bằng cách sử dụng thông tin từ secret của repository
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image dựa trên Dockerfile
      - name: Build Docker image
        run: docker build . -t kitare17/ci_cd:latest

      # Push Docker image lên Docker Hub
      - name: Push Docker image
        run: docker push kitare17/ci_cd:latest
